version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1

    ECR_BASE_URI: "637423596251.dkr.ecr.ap-south-1.amazonaws.com"

    REPO_NAME: "richstream/secureflow"

    CONTAINER_NAME: "Main"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_BASE_URI

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - IMAGE_TAG=$COMMIT_HASH

      - REPO_URI=$ECR_BASE_URI/$REPO_NAME

      - IMAGE_URI=$REPO_URI:$IMAGE_TAG

      - echo "IMAGE_URI=$IMAGE_URI"

  build:
    commands:
      - echo "Build started on $(date)"

      - echo "Building Docker image..."

      - docker build -t $REPO_NAME:$IMAGE_TAG .

      - docker tag $REPO_NAME:$IMAGE_TAG $IMAGE_URI

  post_build:
    commands:
      - echo "Build completed on $(date)"

      - echo "Pushing Docker image..."

      - docker push $IMAGE_URI

      - echo "Creating imagedefinitions.json"

      - echo "[{\"name\":\"$CONTAINER_NAME\",\"imageUri\":\"$IMAGE_URI\"}]" > imagedefinitions.json

      - echo "===== IMAGE DEFINITIONS ====="

      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json