version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Packaging Lambda function...
      - zip -r function.zip .
      - echo "✅ Contents of function.zip:"
      - unzip -l function.zip
artifacts:
  files:
    - function.zip
